"""
Neighbors Module - Point Cloud Neighbor Calculation

This module provides functionality to calculate the nearest neighbors for nodes
in a point cloud, respecting region boundaries. It supports reading from CSV files
generated by the CloudGenerator and computes neighbors strictly within the same region.

Core Functionality:
1. Neighbor Calculation: Finds k-nearest neighbors for each point using KDTree.
2. Region Isolation: Ensures neighbors are only found within the same region.
3. Distance Computation: Optimized distance calculations for neighbor search radius.
4. CSV Integration: Reads point cloud data directly from CSV files.

Key Features:
- Support for CSV input with 'x', 'y', 'classification', 'region' columns.
- KDTree-based efficient neighbor search (O(log n)).
- Region-constrained neighbor finding.
- Fallback to brute force methods if needed (legacy support).

Author: Gerardo Tinoco-Guerrero
Date: March, 2026
Last Modification: March, 2026

Dependencies:
- NumPy
- SciPy
- CSV
- OS
"""

import csv
import logging
import numpy as np
import os
from scipy.spatial import cKDTree

def read_cloud_data(file_path: str):
    """
    Reads point cloud data from a CSV file.
    
    Args:
        file_path (str): Path to the CSV file.
        
    Returns:
        tuple: (points, regions, classifications)
            - points: Nx2 numpy array of (x, y) coordinates.
            - regions: List of region identifiers for each point.
            - classifications: List of classification strings for each point.
            
    Returns (None, None, None) if reading fails.
    """
    points = []
    regions = []
    classifications = []
    
    try:
        # Check if file exists
        if not os.path.exists(file_path):
            logging.error(f"File not found: {file_path}")
            return None, None, None

        with open(file_path, 'r', newline='', encoding='utf-8-sig') as f:
            reader = csv.DictReader(f)
            
            # clean field names (strip whitespace)
            if reader.fieldnames:
                reader.fieldnames = [field.strip() for field in reader.fieldnames]
            else:
                logging.error(f"Empty CSV file: {file_path}")
                return None, None, None
            
            # Check required columns
            required_cols = {'x', 'y', 'region', 'classification'}
            if not required_cols.issubset(set(reader.fieldnames)):
                logging.error(f"Missing required columns in {file_path}. Found: {reader.fieldnames}. Required: {required_cols}")
                return None, None, None
                
            for row in reader:
                try:
                    x = float(row['x'])
                    y = float(row['y'])
                    
                    # Handle region: could be int, float (1.0), or string
                    region_str = str(row['region']).strip()
                    try:
                        region = int(float(region_str))
                    except (ValueError, TypeError):
                        region = region_str # Keep as string if not a number
                        
                    classification = row['classification'].strip()
                    
                    points.append([x, y])
                    regions.append(region)
                    classifications.append(classification)
                except (ValueError, KeyError) as e:
                    logging.warning(f"Skipping invalid row: {row}. Error: {e}")
                    continue
        
        if not points:
            logging.warning(f"No valid points found in {file_path}")
            return None, None, None
            
        return np.array(points), np.array(regions), np.array(classifications)
        
    except Exception as e:
        logging.error(f"Error reading {file_path}: {e}")
        return None, None, None

def compute_neighbors_from_file(file_path: str, nvec: int = 9):
    """
    Computes neighbors for a point cloud file, respecting region boundaries.
    
    Args:
        file_path (str): Path to the CSV file.
        nvec (int): Number of neighbors to find.
        
    Returns:
        numpy.ndarray: Nx(nvec) array where each row contains indices of neighbors.
                       Indices refer to the row numbers in the original file (0-based).
                       Values of -1 indicate fewer than nvec neighbors found.
    """
    points, regions, _ = read_cloud_data(file_path)
    
    if points is None:
        return None
        
    num_points = len(points)
    all_neighbors = np.full((num_points, nvec), -1, dtype=int)
    
    unique_regions = np.unique(regions)
    
    for region in unique_regions:
        # Find indices of points in this region
        region_indices = np.where(regions == region)[0]
        
        if len(region_indices) == 0:
            continue
            
        # Extract points for this region
        region_points = points[region_indices]
        
        # Compute neighbors for this subset
        # Cloud returns indices relative to the subset (0 to len(subset)-1)
        # Pass nvec directly; Cloud handles if nvec > len(region_points)
        local_neighbors = Cloud(region_points, nvec)
        
        # Map local indices back to global indices
        # If local_neighbors[i, j] is k, then the global index is region_indices[k]
        
        for i, global_idx in enumerate(region_indices):
            # Get the row of local neighbors for this point
            local_row = local_neighbors[i]
            
            # Filter out -1s (invalid neighbors)
            valid_mask = local_row != -1
            valid_local_indices = local_row[valid_mask]
            
            # Map to global indices
            global_neighbor_indices = region_indices[valid_local_indices]
            
            # Store in the result array
            all_neighbors[global_idx, :len(global_neighbor_indices)] = global_neighbor_indices
            
    return all_neighbors

def Cloud(p, nvec = 9):
    """
    Cloud
    Function to find the neighbor nodes in a point cloud.
    
    Input:
        p           m x 2 or m x 3  ndarray         Array with the coordinates of the nodes.
        nvec                        integer         Maximum number of neighbors.
    
    Output:
        vec         m x nvec        ndarray         Array with matching neighbors of each node.
    """

    ## Delta computation.
    dist = find_distances(p, mode = 2)

    ## Neighbor search.
    vec = find_neighbors(p, dist, nvec, mode = 3)

    return vec

def find_distances(p, mode = 2):
    """
    find_distances
    Function to find the distances between all the give nodes.
    
    Input:
        p           m x 2 or m x 3  ndarray         Array with the coordinates of the nodes.
        mode                        integer         Choose the way to compute the distances:
                                                    1: brute force
                                                    2: optimized (default)
    
    Output:
        dist                        float           The maximum distance between two consecutive nodes.
    """

    ## Variable initialization.
    m = len(p[:, 0])                                                            # The size if the triangulation is obtained.

    if mode == 1:
        ## Brute Force
        dmin = np.zeros([m, 1]) + 10                                                # dmin initialization with a "big" value.
        for i in np.arange(m):                                                      # For each of the nodes.
            x    = p[i, 0]                                                          # x coordinate of the central node.
            y    = p[i, 1]                                                          # y coordinate of the central node.
            for j in np.arange(m):                                                  # For all the nodes.
                if i != j:                                                          # If the the node is different to the central one.
                    x1 = p[j, 0]                                                    # x coordinate of the possible neighbor.
                    y1 = p[j, 1]                                                    # y coordinate of the possible neighbor.
                    d  = np.sqrt((x - x1)**2 + (y - y1)**2)                         # Distance from the possible neighbor to the central node.
                    dmin[i] = min(dmin[i], d)                                       # Look for the distance to the closest node.
        dist = (3/2)*np.max(dmin)                                                   # The distance is the maximum distance between two consecutive nodes.

    if mode == 2:
        ## Optimized using cKDTree
        # Use cKDTree to find nearest neighbors efficiently (O(N log N) instead of O(N^2))
        p_coords = p[:, :2]
        tree = cKDTree(p_coords)
        
        # Query for the 2 nearest neighbors (k=2)
        # The first neighbor is the point itself (distance 0), the second is the closest other point
        dists, _ = tree.query(p_coords, k=2, workers=-1)
        
        # dists[:, 1] contains the distance to the nearest neighbor
        # If a point has no neighbors (isolated), cKDTree might return inf if k is larger than N,
        # but here k=2 and N is usually >> 2.
        # If N=1, k=2 will return inf for the second column.
        if len(p) > 1:
            min_distances = dists[:, 1]
            # Replace infinite distances (if any) with 0 or handle them
            min_distances = np.where(np.isinf(min_distances), 0, min_distances)
            dist = (3/2) * np.max(min_distances)
        else:
            dist = 0.0

    return dist

def find_neighbors(p, dist, nvec, mode = 2):
    """
    find_neighbors
    Function to find all the neighbors of a node withing a given distance.
    
    Input:
        p           m x 2 or m x 3  ndarray         Array with the coordinates of the nodes.
        dist                        float           Radius distance to look for neighbors.
        nvec                        integer         Maximum number of neighbors.
        mode                        integer         Choose the way to compute the distances:
                                                    1: brute force
                                                    2: optimized
                                                    3: KDTree (default)
    
    Output:
        vec         m x nvec        ndarray         Array with matching neighbors of each node.
    """

    ## Variable initialization.
    m    = len(p[:, 0])                                                             # The size if the triangulation is obtained.
    vec  = np.zeros([m, nvec], dtype = int) - 1                                     # The array for the neighbors is initialized.

    if mode == 1:
        ## Brute Force
        for i in np.arange(m):                                                      # For each of the nodes.
            x, y  = p[i, 0], p[i, 1]                                                # x, y coordinates of the central node.
            temp_neighbors = []                                                     # Create an empty array for neighbors.
            for j in np.arange(m):                                                  # For all the interior nodes.
                if i != j:                                                          # Check that we are not working with the central node.
                    x1, y1 = p[j, 0], p[j, 1]                                       # x, y coordinates of the possible neighbor.
                    d = np.sqrt((x - x1)**2 + (y - y1)**2)                          # Distance from the possible neighbor to the central node.
                    if d < dist:                                                    # If the distance is smaller or equal to the tolerance distance.
                        temp_neighbors.append((d, j))                               # Store the neighbor node.
            temp_neighbors.sort()                                                   # Sort the neighbors by distance.
            for idx, (d, j) in enumerate(temp_neighbors[:nvec]):                    # For each stored neighbor.
                vec[i, idx] = j                                                     # Store the neighbor.
    
    elif mode == 2:
        ## Optimized
        dx = np.expand_dims(p[:, 0 ], 1) - np.expand_dims(p[:, 0], 0)                # Compute dx between all the nodes.
        dy = np.expand_dims(p[:, 1 ], 1) - np.expand_dims(p[:, 1], 0)                # Compute dy between all the nodes.
        radius = np.sqrt(dx**2 + dy**2)                                              # Get the distances from each node to all the others.
        
        for i in range(m):                                                           # For each node.
            neighbors = np.where((radius[i, :] < dist) & (np.arange(m) != i))[0]     # The neighbors are all the nodes within the radius.

            if len(neighbors) > 0:                                                   # If there are more neighbors than the requested.
                neighbors = neighbors[np.argsort(radius[i, neighbors])][:nvec]       # The neighbors are sorted by distance and only the closest nvec neighbors remains.
                vec[i, :len(neighbors)] = neighbors                                  # The nvec neighbors are stored.
            else:
                neighbors = neighbors[np.argsort(radius[i, neighbors])]              # The neighbors are sorted by distance and only the closest nvec neighbors remains.
                vec[i, :len(neighbors)] = neighbors                                  # The neighbors are stored.
    
    elif mode == 3:
        # cKDTree with batch processing
        p_coords = p[:, :2]
        tree = cKDTree(p_coords)
        
        # Query all points at once
        # k=nvec+1 because the first result is the point itself
        distances, indices = tree.query(p_coords, k=nvec+1, distance_upper_bound=dist, workers=-1)
        
        # Handle the results
        # distances and indices are shape (m, nvec+1)
        
        for i in range(m):
            # Get indices and distances for this point
            inds = indices[i]
            dists = distances[i]
            
            # Filter valid neighbors:
            # 1. Distance must be finite (cKDTree returns inf for missing neighbors)
            # 2. Distance must be <= dist (distance_upper_bound handles this largely, but returns inf if exceeded)
            # 3. Index must be < m (cKDTree returns m for missing neighbors)
            # 4. Index must not be i (self)
            
            valid_mask = (dists < float('inf')) & (inds < m) & (inds != i)
            valid_indices = inds[valid_mask]
            
            # We already queried for nvec+1, so after removing self, we have at most nvec
            # Just take the valid ones
            count = min(len(valid_indices), nvec)
            if count > 0:
                vec[i, :count] = valid_indices[:count]

    return vec

def find_neighbors_brute_force(i, p, a, b, dist, nvec):
    """
    Helper function for finding neighbors using brute force method.
    
    Args:
        i (int): Index of the central node.
        p (ndarray): Array of point coordinates.
        a (float): Direction vector x-component.
        b (float): Direction vector y-component.
        dist (float): Maximum search distance.
        nvec (int): Number of neighbors to find.
        
    Returns:
        ndarray: Array of neighbor indices.
    """
    x, y = p[i, 0], p[i, 1]                                                         # x, y coordinates of the central node.
    temp_neighbors = []                                                             # Create an empty array for neighbors.
    for j in np.arange(len(p)):                                                     # For all the nodes.
        if i != j:                                                                  # Check that we are not working with the central node.
            x1, y1 = p[j, 0], p[j, 1]                                               # x, y coordinates of the possible neighbor.
            xt, yt = x1 - x, y1 - y                                                 # Change the "origin" of x and y.
            di = np.sign(np.dot([xt, yt],[a, b]))                                   # Check the direction between (xt, yt) and (a,b).
            d  = np.sqrt((x - x1)**2 + (y - y1)**2)                                 # Distance from the possible neighbor to the central node.
            if di == -1 and d < dist:                                               # If the neighbors are in the correct position and the distance is smaller or equal to the tolerance distance.
                temp_neighbors.append((d, j))                                       # Store the neighbor node.
    temp_neighbors.sort()                                                           # Sort the neighbors by distance.
    neighbors = np.array([j for _, j in temp_neighbors[:nvec]])                     # Extract neighbor indices.
    vec_row   = np.zeros(nvec, dtype=int) - 1                                       # Initialize row with -1.
    if len(neighbors) > 0:
        vec_row[:len(neighbors)] = neighbors                                            # Store the neighbors.
    return vec_row
